[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.1"
  export = ["graphql"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "graphql"
  org = "sarindasatwso2com"
  version = "1.0.0"

